#!/usr/bin/env bash

# Depencencies: awk, tcpdump, jq and mosquitto-clients

# Based on a script created by Reavershark for Linux Essentials course
# at VIVES University College.
# https://github.com/Reavershark

show_help()
{
  echo "Usage: detector [OPTION...]"
  echo "Detect DHCP requests in the network and publish to MQTT"
  echo ""
  echo "  -h                give this help list"
  echo "  -b=[BROKER]       broker to use"
  echo "  -t=[TOPIC]        topic to publish to"
}

broker="labict.be"
topic="network/devices/detected"

while getopts "hb:t:" option; do
    case "$option" in
    h)
        show_help
        exit 0
        ;;
    b)  broker=${OPTARG};;
    t)  topic=${OPTARG};;
    esac
done

if [[ $EUID -ne 0 ]]; then
   echo "This script should probable be run as root"
fi

generate_json()
{
cat <<EOF
{
    "time": "$(date)",
    "mac": "$mac",
    "ip": "$ip",
    "hostname": $hostname
}
EOF
}

set buffer

tcpdump -i any port 67 or port 68 -len -vvv 2>/dev/null | while read line; do
    if [ ! "$line" = "END Option 255, length 0" ]; then
        buffer+=$line
        buffer+="\n"
    elif echo -e $buffer | grep "Client-Ethernet-Address" &> /dev/null; then
        if echo -e $buffer | grep "Requested-IP" &> /dev/null; then 
            mac=$(echo -e $buffer | grep "Client-Ethernet-Address" | awk '{print $2}')
            ip=$(echo -e $buffer | grep "Requested-IP" | awk '{print $6}')
            hostname=$(echo -e $buffer | grep "Hostname" | awk '{print $6}')

            # Hostname is not always provided
            [ -z $hostname ] && hostname="\"unknown\""

            echo "Intercepted DHCP Request:"
            echo $(generate_json) | jq .

            # Send to MQTT broker
            echo "Publishing to ${broker} @ ${topic}"
            mosquitto_pub -V mqttv311 -h "${broker}" -t "${topic}" -m "$(generate_json)" | jq .
        fi
        buffer=
    fi
done
